name: Build Linux Packages
on:
  push:
    tags:
      - "*.*.*"

  workflow_dispatch:

env:
  PACKAGE_NAME: cockpit-guacamole
  DIST: el9
  ARCH: noarch

jobs:
  build_tarball:
    name: Build source archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 22.x

      - name: Build plugin
        run: |
          tree
          npm ci
          npm run build

      - name: Create source archive
        run: |
          mkdir ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}
          cp -r dist/* ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}/
          cp LICENSE ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}/
          rm -f ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}/*.map
          tar -czvf ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}.tar.gz ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}

      - name: Upload source archive as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}.tar.gz
          path: ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}.tar.gz

  build_rpm:
    name: Build .rpm package
    needs: build_tarball
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download source archive
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}.tar.gz

      - name: Install rpmbuild
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Replace version in RPM spec
        run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{ github.ref_name }}/' ${{ env.PACKAGE_NAME }}.spec

      - name: Build RPM
        run: |
          mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          cp ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}.tar.gz ~/rpmbuild/SOURCES/
          rpmbuild -ba ${{ env.PACKAGE_NAME }}.spec

      - name: Upload .rpm package as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
          path: ~/rpmbuild/RPMS/${{ env.ARCH }}/*.rpm

  build_deb:
    name: Build .deb package
    needs: build_rpm
    runs-on: ubuntu-latest
    steps:
      - name: Download .rpm artifact
        uses: actions/download-artifact@v8
        id: download
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm

      - name: Convert .rpm to .deb
        run: |
          sudo apt install -y alien
          sudo alien -k --verbose --to-deb *.rpm

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.deb
          path: ${{ env.PACKAGE_NAME }}*.deb

  release:
    name: Create release with all assets
    needs: [build_tarball, build_rpm, build_deb]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Download cached rpm, deb, and tar.gz artifacts
        uses: actions/download-artifact@v8

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}.tar.gz/*.tar.gz
            ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm/**/*.rpm
            ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.deb/**/*.deb
